### ISSUE TITLE
Getting exception on eventbus sendFuture

### ISSUE THREAD

**Issue by ezequielventura** [vert-x3/vertx-lang-scala#47]
I'm running the following code, I only included the relevant code:

```
import io.vertx.core.buffer.Buffer
import io.vertx.lang.scala.ScalaVerticle
import io.vertx.lang.scala.json.JsonObject
import io.vertx.scala.core.eventbus.{DeliveryOptions, Message}

import scala.concurrent.Future
import scala.util.{Failure, Success}
class HttpEndpointVerticle extends ScalaVerticle{

  override def startFuture(): Future[Unit] = {
    // address is a string
    // params is a JsonObject
    // sOpt is a DeliveryOptions
    val eb = vertx.eventBus
     eb.sendFuture[Message[Buffer]](address, params, dOpt).onComplete{
       case Success(result) => {
         val r = result.body().body()
         val response = routingContext.response
         response.putHeader("content-type", "application/json")
         response.end(r)
        }
        case Failure(cause) => {
          routingContext.response().setStatusCode(404).end(cause.getMessage())
        }
     }
  }
}
```

and I get the following error:

> Failed executing on contet 
java.lang.NoSuchMethodException: io.vertx.scala.core.eventbus.Message$.apply(io.vertx.core.buffer.Buffer)
	at java.lang.Class.getMethod(Class.java:1786)
	at io.vertx.lang.scala.Converter$.toScala(Converter.scala:27)
	at io.vertx.scala.core.eventbus.Message.body(Message.scala:52)
	at com.anubor.dingo.vertx.scala.api.rest.HttpEndpointVerticle.$anonfun$startFuture$3(HttpEndpointVerticle.scala:56)
	at com.anubor.dingo.vertx.scala.api.rest.HttpEndpointVerticle.$anonfun$startFuture$3$adapted(HttpEndpointVerticle.scala:54)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at io.vertx.lang.scala.VertxExecutionContext.$anonfun$execute$1(VertxExecutionContext.scala:36)
	at io.vertx.scala.core.Context.$anonfun$runOnContext$1(Context.scala:84)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)

I can tell that the message gets sent and the verticle that replies produces a reply without errors.

Thanks in advance for looking into my issue.

**Comment by ezequielventura** [comment]
I tried the send method that takes a handler and it worked, after that I tried to reproduce the exception in a simpler example, but I couldn't. So I rolled back the code, recompiled and I finally got it working. Sadly I couldn't find out what was wrong in the first place, but I'm quite sure it was my mistake.
