### ISSUE TITLE
Possible regression on JsonObject in version 3.5.1

### ISSUE THREAD

**Issue by lecogiteur** [vert-x3/vertx-lang-scala#66]
Hi,

When I do

```scala
val aJson = new JsonObject("{\"key\": [\"value\"]}")
aJson.copy()
```

I have this error (only in version 3.5.1). Need to deploy before at least a verticle (JsonInit is call in VerticleExecutionContext)

```
java.lang.IllegalStateException: Illegal type in JsonObject: class scala.collection.immutable.$colon$colon
        at io.vertx.core.json.Json.checkAndCopy(Json.java:210)
        at io.vertx.core.json.JsonObject.copy(JsonObject.java:796)
        at io.vertx.core.impl.DeploymentManager.doDeploy(DeploymentManager.java:461)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:203)
        at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:76)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:171)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:143)
        at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:131)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:665)
        at io.vertx.scala.core.Vertx.deployVerticleFuture(Vertx.scala:566)
```

It's due to we register now with io.vertx.lang.scala.JsonInit the scala module in ObjectMapper. So now array is sequence and not an java.util.ArrayList.

I have found a workaround 

```scala
import scala.collection.JavaConverters._
val newJson = Json.obj(aJson.getMap.asScala.toSeq: _*)
newJson.copy()
```

But I think It's a regression because there is lots of code in Java which produce JsonObject from String perhaps need to override and extends JsonObject with a scala object (or implicit conversion). 

With version 3.5.0 there is no problem:
This works
```scala
val aJson = new JsonObject("{\"key\": [\"value\"]}")
aJson.copy()
```

**Comment by codepitbull** [comment]
Fix will be part of 3.5.2

**Comment by blueberrynotblue** [comment]
@codepitbull  Will the fat-jar size problem be solved in 3.5.2?

**Comment by codepitbull** [comment]
@blueberrynotblue I can't find the issue for that in vertx-lang-scala. Did you open it against one of the other vert.x projects?

**Comment by codepitbull** [comment]
I opened a new issue (https://github.com/vert-x3/vertx-lang-scala/issues/68). This won't make it into 3.5.2 as it isn't really a bug and needs more testing. Current master reduced size by almost 50%.
