### ISSUE TITLE
Nullable regression in codegen TCK

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-lang-scala#78]
```
Running io.vertx.lang.scala.tck.ApiTest
Tests run: 59, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.121 sec <<< FAILURE! - in io.vertx.lang.scala.tck.ApiTest
testNullJsonParams should work(io.vertx.lang.scala.tck.ApiTest)  Time elapsed: 0.01 sec  <<< ERROR!
java.lang.NullPointerException: null
	at io.vertx.scala.codegen.testmodel.TestInterface.methodWithNullJsonParams(TestInterface.scala:411)
	at io.vertx.lang.scala.tck.ApiTest.$anonfun$new$158(ApiTest.scala:650)

testNullJsonHandlerAsyncResultParams should work(io.vertx.lang.scala.tck.ApiTest)  Time elapsed: 0.016 sec  <<< ERROR!
org.scalatest.exceptions.TestFailedException: null did not equal None
	at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:528)
	at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:527)
	at org.scalatest.FlatSpec.newAssertionFailedException(FlatSpec.scala:1685)
	at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:501)
	at io.vertx.lang.scala.tck.ApiTest.$anonfun$new$174(ApiTest.scala:698)
```

**Comment by codepitbull** [comment]
Will take care of it.

**Comment by codepitbull** [comment]
All clear in 3.x branches.
4.0 Branch is currently  a preview and not affected by this.
